name: Build

on: [push]

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js (LTS)
              uses: actions/setup-node@v2
            - name: Authenticate NPM
              uses: DimensionDev/github-token-action@latest
              with:
                  registry: true
            - name: Install
              run: npx pnpm install
            - name: Build
              run: npm run build
            - name: Publish to GitHub Package (unstable)
              run: ./scripts/publish-to-github.sh
